version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravelapp/public
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 5
      runas: root
    - location: scripts/start_server
      timeout: 5
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 5
      runas: root
